"""
app/schemas/skill.py
Pydantic schemas for skill request and result payloads.
"""

from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List

class SkillRequest(BaseModel):
    skill_name: str = Field(..., description="Name of the skill to execute (e.g. system-status)")
    inputs: Dict[str, Any] = Field(default_factory=dict, description="Dynamic key-value arguments for skill runtime")
    domain: str = Field("personal-os", description="Domain context namespace")

class SkillResult(BaseModel):
    skill_name: str = Field(..., description="Name of the executed skill")
    success: bool = Field(..., description="Status flag of success/failure")
    actions_taken: List[Dict[str, Any]] = Field(default_factory=list, description="List of system actions executed")
    files_written: List[str] = Field(default_factory=list, description="Files outputted by this skill")
    output_summary: str = Field(..., description="Human-readable markdown summary generated by the skill execution")
    error: Optional[str] = Field(None, description="Exception message details if success is False")